library("safetyGraphics")
library(shiny)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(tidyverse)
library(plotly)
library(gt)
library(yaml)

source("./R/nepexplorerMod.R")
source("./R/patient_profile_charts.R")
source("./R/patient_profile_mod.R")
source("./R/creatinine_scatter_mod.R")
source("./R/creatinine_scatter_charts.R")

charts <- makeChartConfig()
charts$nepexplorer <- prepareChart(read_yaml("./nepexplorer.yaml"))
safetyGraphicsApp(charts = charts)