env: safetyGraphics
label: Nep Explorer - Module
name: nepexplorerMod
type: module
package: nepExplorer
order: 9
domain:
  - labs
  - vitals
  - dm
workflow:
  ui: nepexplorer_ui
  server: nepexplorer_server
links:
  nepExplorer: https://github.com/SafetyGraphics/nep-explorer
