export default function styles() {
    const styles = [
        '.wc-framework {',
        '    width: 100%;',
        '    display: inline-block;',
        '}',
        '.wc-hidden {',
        '    display: none !important;',
        '}',
        '.wc-invisible {',
        '    visibility: hidden;',
        '}',

        '.wc-column {',
        '    display: inline-block;',
        '}',
        '.wc-section {',
        '    display: inline-block;',
        '    width: 100%;',
        '}',
        '.wc-component {',
        '    display: inline-block;',
        '    width: 100%;',
        '}',

        /***--------------------------------------------------------------------------------------\
		  left column
        \--------------------------------------------------------------------------------------***/

            '.wc-column--left {',
            '    width: 20%;',
            '}',

            /****---------------------------------------------------------------------------------\
              controls
            \---------------------------------------------------------------------------------****/

                '.wc-section--controls {',
                '}',

        /***--------------------------------------------------------------------------------------\
		  right column
        \--------------------------------------------------------------------------------------***/

            '.wc-column--right {',
            '    width: 79%;',
            '}',

            /****---------------------------------------------------------------------------------\
              KDIGO scatter plot
            \---------------------------------------------------------------------------------****/

                '.wc-section--population {',
                '    width: 79%;',
                '}',
                '.wc-component--kdigo-scatter-plot circle.wc-data-mark {',
                '    cursor: pointer;',
                '    stroke: black;',
                '    fill-opacity: 1;',
                '    stroke-width: 1;',
                '}',
                '.wc-component--kdigo-scatter-plot circle.wc-data-mark:hover {',
                '    stroke-width: 3;',
                '}',
                '.wc-component--kdigo-scatter-plot circle.wc-data-mark.wc-selected {',
                '    stroke-width: 3;',
                '}',
                '.kdigo-stage {',
                '    stroke: black;',
                '}',
                '.wc-component--kdigo-scatter-plot .tick line {',
                '    stroke-opacity: .4;',
                '}',
                '.wc-component--kdigo-legend {',
                '    width: 20%;',
                '    float: right;',
                '}',
                '.wc-component--kdigo-legend .interactivity {',
                '    display: none;',
                '}',
                '.wc-component--kdigo-legend table {',
                '    border-collapse: collapse;',
                '}',
                '.wc-component--kdigo-legend thead {',
                '    border-top: 2px solid #999;',
                '    border-bottom: 2px solid #999;',
                '}',
                '.wc-component--kdigo-legend thead tr {',
                '    padding: 0.1em;',
                '}',
                '.wc-component--kdigo-legend tbody {',
                '    border-bottom: 2px solid #999;',
                '}',
                '.wc-component--kdigo-legend tbody {',
                '    border-bottom: 2px solid #999;',
                '}',
                '.wc-component--kdigo-legend tbody tr {',
                '    padding: 0.1em;',
                '}',
                '.wc-component--kdigo-legend tbody td {',
                '    text-align: center;',
                '    font-size: 0.9em;',
                '    padding: 0 0.5em 0 0.5em;',
                '}',

            /****---------------------------------------------------------------------------------\
              participant details
            \---------------------------------------------------------------------------------****/

                '.wc-section--participant {',
                '}',
                '.wc-header {',
                '    border-top: 2px solid black;',
                '    border-bottom: 2px solid black;',
                '    padding: 0.2em;',
                '    font-weight: bold;',
                '}',
                '.wc-component__details-clear {',
                '    float: right;',
                '    margin: 0.5em;',
                '}',
                '.wc-component__details-participant {',
                '    list-style: none;',
                '    padding: 0;',
                '}',
                '.wc-details__li {',
                '    display: inline-block;',
                '    text-align: center;',
                '    padding: 0.5em;',
                '}',
                '.wc-details__label {',
                '    font-size: 0.8em;',
                '}',
                '.wc-details__value {',
                '}',
                '.wc-subcomponent {',
                '    display: inline-block;',
                '    width: 100%;',
                '}',
                '.wc-component--time-series-chart {',
                '    width: 100%;',
                '}',
                '.wc-diff .wc-hover-line {',
                '    stroke: #fff;',
                '    stroke-width: 16;',
                '    stroke-opacity: 0;',
                '}',
                '.wc-diff .wc-visible-line {',
                '    stroke-width: 2;',
                '    stroke: #8E4C6A;',
                '    stroke-dasharray: 3 3;',
                '}',
                '.wc-diff .wc-visible-line.wc-hovered {',
                '    stroke-dasharray: 0;',
                '}',
                '.wc-component--time-series .wc-chart {',
                '    width: 80%;',
                '    display: inline-block;',
                '}',
                '.wc-component--time-series .axis-title {',
                '    font-size: 14px;',
                '    font-weight: bold;',
                '}',
                '.legend {',
                '    width: 20% !important;',
                '    display: inline-block;',
                '    float: right;',
                '}',
                '.legend-item {',
                '    float: left;',
                '    clear: left;',
                '    margin-right: 0 !important;',
                '}',
                '.legend-mark-text {',
                '    display: none;',
                '}',
                '.legend-label {',
                '    margin-right: .55em;',
                '    font-size: 12px;',
                '}',
                '.legend-color-block {',
                '}',
                '.wc-reference-lines {',
                '    cursor: help;',
                '}',
                '.wc-reference-line {',
                '    x1: 0;',
                '    stroke: #999;',
                '    stroke-dasharray: 3 3;',
                '}',
                '.wc-reference-label {',
                '    text-anchor: end;',
                '    alignment-baseline: baseline;',
                '    fill: #999;',
                '}'
    ];

    const style = document.createElement('style');
    style.type = 'text/css';
    style.innerHTML = styles.join('\n');
    document.getElementsByTagName('head')[0].appendChild(style);

    return style;
}
