export default function styles() {
    const styles = [
        '.wc-framework {',
        '    width: 100%;',
        '    display: inline-block;',
        '}',
        '.wc-hidden {',
        '    display: none !important;',
        '}',
        '.wc-invisible {',
        '    visibility: hidden;',
        '}',
        '.wc-header {',
        '    font-size: 20px;',
        '    font-weight: bold;',
        '}',
        '.wc-row {',
        '    width: 100%;',
        '    display: inline-block;',
        '}',
        '.wc-component--chart {',
        '    display: inline-block;',
        '}',
        '.wc-component--kdigo-scatter-plot {',
        '    width: 48%;',
        '    float: left;',
        '}',
        '.wc-component--time-series {',
        '    width: 48%;',
        '    float: right;',
        '}',
        '.wc-component--time-series-chart {',
        '    width: 100%;',
        '}',
        '.kdigo-stage {',
        '    stroke: black;',
        '}',
        '.wc-component--kdigo-scatter-plot circle.wc-data-mark {',
        '    cursor: pointer;',
        '    stroke: black;',
        '    fill-opacity: 1;',
        '    stroke-width: 1;',
        '}',
        '.wc-component--kdigo-scatter-plot circle.wc-data-mark:hover {',
        '    stroke-width: 3;',
        '}',
        //'.wc-framework .wc-component--chart:nth-child(3n-2) {',
        //'    float: left;',
        //'}',
        //'.wc-framework .wc-component--chart:nth-child(3n-1) {',
        //'    margin: 0 2%;',
        //'}',
        //'.wc-framework .wc-component--chart:nth-child(3n) {',
        //'    float: right;',
        //'}',
    ];

    const style = document.createElement('style');
    style.type = 'text/css';
    style.innerHTML = styles.join('\n');
    document.getElementsByTagName('head')[0].appendChild(style);

    return style;
}
