# library(shiny)
# library(dplyr)
# library(ggplot2)
# library(RColorBrewer) <- need to turn these into roxygen documentation e.g. # import RColorBrewer
# library(tidyverse)
# library(plotly)
# library(gt)

#' Run the core safetyGraphics App
#'
#' @param domainData named list of data.frames to be loaded in to the app. Sample AdAM data from the safetyData package used by default
#' @param meta data frame containing the metadata for use in the app. If no metadata is provided, metatdata is generated by `makeMeta()`. 
#' @param charts list of charts in the format produced by safetyGraphics::makeChartConfig()
#' @param mapping list specifying the initial mapping values for each data mapping for each domain (e.g. list(aes= list(id_col='USUBJID', seq_col='AESEQ')). 
#' @param autoMapping boolean indicating whether the app should attempt to automatically detect data standards and generate mappings for the data provided. Values specified in the `mapping` parameter overwrite automatically generated mappings when both are found. Defaults to true.
#' @param filterDomain domain used for the data/filter tab. Demographics ("`dm`") is used by default. Using a domain that is not one record per participant is not recommended. 
#' @param chartSettingsPaths path(s) where customization functions are saved relative to your working directory. All charts can have initialization (e.g. myChart_Init.R) and static charts can have charting functions (e.g. myGraphic_Chart.R).   All R files in this folder are sourced and files with the correct naming convention are linked to the chart. See the Custom Charts vignette for more details. 
#' @param runNow Should the shiny app object created be run directly? Helpful when writing  functions to dispatch to shinyapps, rsconnect, or shinyproxy.
#'
#' @import shiny
#' @import dplyr
#' @import ggplot2
#' @import RColorBrewer
#' @import tidyverse
#' @import plotly
#' @import gt
#' @import htmlwidgets
#' 
#' @export
nepexplorer_ui <- function(id) {
  ns <- NS(id)

  sidebar <- sidebarPanel(selectizeInput(
    ns("measures"),
    "Select Measures",
    multiple = TRUE,
    choices = c("")
  ))
  
  
  main <- mainPanel(
     # Scatterplot placeholder
      creatinineScatterUI(ns("scatter")),
      br(),
      br(),
      # Patient Profile (demo tables + lab line charts)
      patientProfileUI(ns("patprofile")) 
  )

  ui <- sidebarLayout(
    sidebar,
    main,
    position = c("right"),
    fluid = TRUE
  )

  return(ui)
}


#' Run the core safetyGraphics App
#'
#' @param domainData named list of data.frames to be loaded in to the app. Sample AdAM data from the safetyData package used by default
#' @param meta data frame containing the metadata for use in the app. If no metadata is provided, metatdata is generated by `makeMeta()`. 
#' @param charts list of charts in the format produced by safetyGraphics::makeChartConfig()
#' @param mapping list specifying the initial mapping values for each data mapping for each domain (e.g. list(aes= list(id_col='USUBJID', seq_col='AESEQ')). 
#' @param autoMapping boolean indicating whether the app should attempt to automatically detect data standards and generate mappings for the data provided. Values specified in the `mapping` parameter overwrite automatically generated mappings when both are found. Defaults to true.
#' @param filterDomain domain used for the data/filter tab. Demographics ("`dm`") is used by default. Using a domain that is not one record per participant is not recommended. 
#' @param chartSettingsPaths path(s) where customization functions are saved relative to your working directory. All charts can have initialization (e.g. myChart_Init.R) and static charts can have charting functions (e.g. myGraphic_Chart.R).   All R files in this folder are sourced and files with the correct naming convention are linked to the chart. See the Custom Charts vignette for more details. 
#' @param runNow Should the shiny app object created be run directly? Helpful when writing  functions to dispatch to shinyapps, rsconnect, or shinyproxy.
#'
#' @import shiny
#' @import dplyr
#' @import ggplot2
#' @import RColorBrewer
#' @import tidyverse
#' @import plotly
#' @import gt
#' @import htmlwidgets
#' 
#' @export
nepexplorer_server <- function(input, output, session, params){
      ns <- session$ns
      
      
      # Populate sidebar control with measures and select all by default
      observe({
        measure_col <- params()$settings$labs$measure_col
        measures <- unique(params()$data[[measure_col]])
        updateSelectizeInput(session,
                             "measures",
                             choices = measures,
                             selected = measures
        )
        
      })
      
      # map columns for adbds dataset 
      adlb <- reactive({
        
        params()$data$labs %>% 
          rename( # I suppose this will break if the name already exists in dataframe - can fix this later, you get the idea
            USUBJID = params()$settings$labs$id_col,
            DY = params()$settings$labs$studyday_col,
            TEST = params()$settings$labs$measure_col,
            STRESN = params()$settings$labs$value_col,
            VISIT = params()$settings$labs$visit_col,
            VISITN = params()$settings$labs$visit_order_col,
            BLFL = params()$settings$labs$baseline_flag
          )
        
      
        
      })
      
      # get procossed data - amy not ened this??
      processed_creatinine_data <- reactive({
        creatinineScatterServer("scatter", df = adlb(), params= params()) 
        
      })
      
      # subject id return from plotly click event
      selected_subject <- reactive({
        processed_creatinine_data()[event_data("plotly_click", source = "scatter")$pointNumber,]$USUBJID
      })
      
      
      #Patient Profile (demo tables + lab line charts)
      observeEvent(selected_subject(),{
        
        if(length(selected_subject()) == 1){ # avoid triggering patient profiles if there isn't a subject
          patientProfileServer("patprofile", df = adlb(), subj_id = selected_subject())
        }
      },  ignoreInit = TRUE)
      
}

